local Mapper=R('baseline/Mapper')
local Adapter=R('baseline/InputAdapter')
local Manager=R('baseline/NoteManager')
local Scheduler=R('baseline/Scheduler')
local n={note=60,token='a',startTime=1,endTime=3,keyReleaseTime=1.2,velocity=.7,parts={hand='Right'}}
check('baseline pedal preserves finger release',function()
 local e=Mapper.toEvents({n},{expression={holdScale=1,articulationInfluence=0,velocityInfluence=0,minHoldMs=6,maxHoldMs=2000}})[1]
 assert(math.abs(e.holdMs-200)<.001)
end)
check('baseline retrigger reserves release gap',function()
 local b=table.clone(n);b.startTime=1.1;b.keyReleaseTime=1.3
 local e=Mapper.toEvents({n,b},{expression={holdScale=1,releaseGapMs=7}})
 assert(e[1].holdMs<=93.001)
end)
check('baseline old delayed release cannot release retrigger',function()
 local a=Adapter.new();a:strike('a',{holdMs=100});advance(.05);a:strike('a',{holdMs=200});advance(.06)
 assert(a.heldStrike.A~=nil);advance(.15);assert(a.heldStrike.A==nil)
end)
check('baseline panic cancels pending holds',function()
 local a=Adapter.new();local m=Manager.new(a);a:strike('a',{holdMs=200});m:releaseAll();local c=#keyLog;advance(.3);assert(#keyLog==c and next(a.heldStrike)==nil)
end)
check('baseline pause and seek release',function()
 local a=Adapter.new();local m=Manager.new(a);local s=Scheduler.new(m)
 s:setEvents({{time=0,action='strike',token='a',holdMs=200}},2);s:play();advance(.01);s:pause();assert(next(a.heldStrike)==nil);s:seek(.7,false);assert(s:getPosition()==.7)
end)
check('baseline captures 260 ms adapter cap',function()
 local a=Adapter.new();a:strike('a',{holdMs=900});advance(.261);assert(a.heldStrike.A==nil)
end)
