return {
    version = 11,
    midiFolders = {
        "Delta/Workspace/MIDI",
        "Delta/Workspace/Midis",
        "Delta/Workspace/Songs",
        "Delta/Workspace/Music",
        "Delta/Workspace",
        "Workspace/MIDI",
        "MIDI",
    },
    playback = {
        speed = 1.0,
        mode = "Both",
        transpose = 0,
        rangeMode = "SmartOctave",
        lateMode = "CatchUp",
        maxLateMs = 140,
        chordWindowMs = 9,
        collisionWindowMs = 2.5,
        loopSong = false,
        quantization = "Off",
        maxSimultaneousKeys = 16,
        maxNotesPerSecond = 0,
        triggerMode = "Tap",
        loopA = nil,
        loopB = nil,
        expression = {
            enabled = true,
            nativeVelocity = true,
            durationMode = "MIDI",
            minHoldMs = 16,
            maxHoldMs = 900,
            holdScale = .96,
            releaseGapMs = 7,
            velocityInfluence = .12,
            articulationInfluence = .78,
        },
    },
    parts = {
        splitMode = "Auto",
        splitNote = 60,
        percussion = false,
        enabledTracks = {},
        enabledChannels = {},
    },
    humanize = {
        preset = "Pianist",
        enabled = true,
        strength = .68,
        timingMs = 10,
        phraseMs = 11,
        handMs = 6,
        microMs = 2.8,
        chordSpreadMs = 11,
        rubatoMs = 10,
        durationVariation = .027,
        latencyMs = 0,
        velocityPreservation = .88,
        dynamicContour = .52,
        seedMode = "Auto",
        fixedSeed = 12345,
    },
    ui = {
        state = "Full",
        activeTab = "Library",
        librarySource = "Local",
        floatingX = .84,
        floatingY = .72,
        pianoRoll = true,
        pianoRollLookAhead = 2.6,
        songFilter = "All",
        songSort = "A-Z",
        performanceMode = false,
        transitions = true,
        lastSeenChangelog = "",
    },
    cloud = {
        enabled = true,
        provider = "Dodo",
        timeoutSeconds = 6,
        downloadFolder = "Delta/Workspace/MIDI/Cloud",
    },
    pianoProfile = "RobloxVirtualPiano61",
}
