return {
    version = 10,
    midiFolders = {
        "Delta/Workspace/MIDI",
        "Delta/Workspace/Midis",
        "Delta/Workspace/Songs",
        "Delta/Workspace/Music",
        "Delta/Workspace",
        "Workspace/MIDI",
        "MIDI",
    },
    playback = {
        speed = 1.0,
        mode = "Both",
        transpose = 0,
        rangeMode = "SmartOctave",
        lateMode = "CatchUp",
        maxLateMs = 140,
        chordWindowMs = 8,
        collisionWindowMs = 2.5,
        loopSong = false,
        quantization = "Off",
        maxSimultaneousKeys = 16,
        maxNotesPerSecond = 0,
        triggerMode = "Tap",
        loopA = nil,
        loopB = nil,
        expression = {
            enabled = true,
            nativeVelocity = true,
            durationMode = "MIDI",
            minHoldMs = 18,
            maxHoldMs = 650,
            holdScale = .90,
            releaseGapMs = 8,
            velocityInfluence = .12,
            articulationInfluence = .78,
        },
    },
    parts = {
        splitMode = "Auto",
        splitNote = 60,
        percussion = false,
        enabledTracks = {},
        enabledChannels = {},
    },
    humanize = {
        preset = "Pianist",
        enabled = true,
        strength = .14,
        timingMs = 5,
        chordSpreadMs = 4,
        durationVariation = .012,
        handIndependence = .30,
        phraseExpression = .40,
        rubato = .08,
        swingMs = .5,
        latencyMs = 0,
        velocityPreservation = .90,
        dynamicContour = .42,
        seedMode = "Auto",
        fixedSeed = 12345,
    },
    ui = {
        state = "Full",
        activeTab = "Library",
        librarySource = "Local",
        floatingX = .84,
        floatingY = .72,
        pianoRoll = true,
        pianoRollLookAhead = 3.5,
        songFilter = "All",
        songSort = "A-Z",
        performanceMode = false,
    },
    cloud = {
        enabled = true,
        provider = "Dodo",
        autoProbe = false,
        downloadFolder = "Delta/Workspace/MIDI/Cloud",
    },
    pianoProfile = "RobloxVirtualPiano61",
}
