return {
    version = 12,
    midiFolders = {
        "Delta/Workspace/MIDI",
        "Delta/Workspace/Midis",
        "Delta/Workspace/Songs",
        "Delta/Workspace/Music",
        "Delta/Workspace",
        "Workspace/MIDI",
        "MIDI",
    },
    playback = {
        speed = 1.0,
        speedSteps = {.25,.5,.75,.9,1.0,1.1,1.25,1.5,1.75,2.0},
        mode = "Both",
        transpose = 0,
        rangeMode = "SmartOctave",
        lateMode = "CatchUp",
        maxLateMs = 140,
        chordWindowMs = 10,
        collisionWindowMs = 2.5,
        loopSong = false,
        quantization = "Off",
        maxSimultaneousKeys = 16,
        maxNotesPerSecond = 0,
        triggerMode = "Tap",
        loopA = nil,
        loopB = nil,
        expression = {
            enabled = true,
            nativeVelocity = true,
            durationMode = "MIDI",
            minHoldMs = 14,
            maxHoldMs = 1400,
            holdScale = .96,
            releaseGapMs = 7,
            velocityInfluence = .14,
            articulationInfluence = .82,
        },
    },
    parts = {
        splitMode = "Auto",
        splitNote = 60,
        percussion = false,
        enabledTracks = {},
        enabledChannels = {},
    },
    humanize = {
        preset = "Pianist",
        enabled = true,
        strength = .72,
        timingMs = 11,
        phraseMs = 14,
        handMs = 7,
        microMs = 2.6,
        chordSpreadMs = 12,
        rubatoMs = 12,
        localTempoPercent = 2.2,
        motifVariation = .48,
        durationVariation = .03,
        latencyMs = 0,
        velocityPreservation = .86,
        dynamicContour = .58,
        seedMode = "Auto",
        fixedSeed = 12345,
    },
    ui = {
        state = "Full",
        restoreState = "Compact",
        activeTab = "Library",
        librarySource = "Local",
        floatingX = .86,
        floatingY = .72,
        pianoRoll = true,
        pianoRollLookAhead = 2.8,
        songFilter = "All",
        songSort = "A-Z",
        transitions = true,
        lastSeenChangelog = "",
        accent = "Violet",
    },
    cloud = {
        enabled = true,
        provider = "Dodo",
        timeoutSeconds = 5,
        totalDeadlineSeconds = 12,
        downloadFolder = "Delta/Workspace/MIDI/Cloud",
    },
    pianoProfile = "RobloxVirtualPiano61",
}
